### ISSUE TITLE
Loading Indicator

### ISSUE THREAD

**Issue by LouisOh** [kogmbh/ViewerJS#256]
Hi, how do i add a loading indicator when the pdf is still loading?

**Comment by benyaminl** [comment]
Any Update on Loading indicator?

UPDATE :
see this (https://github.com/webodf/ViewerJS/issues/96#issuecomment-105753892), so in the end, we can just add a CSS with gif loading indicator like this 
```css
<style>
            #canvasContainer {background-image: url(images/load.gif)}
        </style>
```
This works for me to be honest 
![image](https://user-images.githubusercontent.com/2817332/88539546-ab12b800-d03b-11ea-947e-7f5bdbf70d1d.png)
